### ISSUE TITLE
Make properties in BaseRequestBuilder public

### ISSUE THREAD

**Issue by svrooij** [microsoft/kiota-abstractions-dotnet#113]
These properties are now marked as `protected` by making them `public` you could easily extend the requestbuilder using extension methods.

https://github.com/microsoft/kiota-abstractions-dotnet/blob/d6d836a90fb81fa894eee5d89660d8145a2e5029/src/BaseRequestBuilder.cs#L16-L20

### Background

The new Graph SDK for .NET (even the beta version), does not contain all the endpoints available. By extending the request builder we could easily implement those additional endpoints and have the same experience. No we cannot use the `PathParameters` or the `RequestAdapter` even though these are available from other classes.

**Comment by baywet** [comment]
Thanks for reaching out.
Solving any gap using extension methods is something we refrain from as it will only work in dotnet.
We'd rather fix the metadata or conversion process so it benefits every language.
Can you open issues against the SDK repository to pinpoint what's missing please?

**Comment by svrooij** [comment]
I fully understand, the SDKs should be better. Will do that as well, but it was just background.

 I don’t see why those Properties have to be protected. It would also help if you just want to try something out. Is there some architectural decision behind that? Seems like a small change that allows extensibility.

we are planning to also use kiota for our own projects, and we would like extensibility.

**Comment by baywet** [comment]
Can you provide specific scenarios that having access to these properties would allow you to build? Without using extension methods.

**Comment by svrooij** [comment]
I'm thinking of extensions. So you have this basic api, and build some additional features. Then you can ship those additional features to some beta testers as a nuget with extension methods.

The Graph API currently has two packages, one for `v`1.0` and one for `beta`, if you where to allows extensions, you could have 1 package for the `v1.0` and a package with the extensions that are currently in beta. If the developer then wants to migrate to the production version of the api he would not have to change the namespace of all elements. 

Installing a newer version for the `v1.0` api would then be a breeze, just a package upgrade, where you remove extensions from the beta package and add them to the regular package.

**Comment by baywet** [comment]
Thanks for sharing. The other aspect to making those properties public is they will start showing up with the auto-completion on the fluent API surface e.g.:

```csharp
client.Me.Messages.UrlTemplate
```

which will be distracting to most users.
For that reason (and the extensibility pattern only being available in CSharp), we're not planning to change the access to those properties.

**Comment by svrooij** [comment]
I did not think of this, you're right. How about making all the request builders partial. That would enable extensibility without showing all those "not to be used by regular users" properties to users.

**Comment by baywet** [comment]
This solution would be limited to CSharp and TypeScript as far as I can tell. We've already had a long conversation about extensibility [here](https://github.com/microsoft/kiota/issues/908) during the early days of Kiota and couldn't come to a conclusion that'd be satisfactory to most languages.

**Comment by svrooij** [comment]
Hi @baywet I was not talking about **all** languages. I was talking about `C#`. You could allow a situation where some languages would support extending the api and some languages won't (like Java so it seems).

In javascript/TypeScript you are able to access private properties if you ignore the boundries (like described [here](https://dev.to/danywalls/testing-private-methods-in-typescript-3np5#use-array-access-for-the-private-members).

Let me revert the question, what is against making all the requestbuilders generated by Kiota `partial` for C#? This would allow the needed extensibility for C# since the language supports it. And maybe other developers like it so much that you guys decide to enable similar functionality in other languages (that support either partials or extension methods) as well.

**Comment by svrooij** [comment]
@MartinM85 This was not only created for the missing metadata. It was created to allow extending the request builders for all apps generated by Kiota.

**Comment by baywet** [comment]
Let's leave the gap in the metadata outside of this conversion so we can focus on the extensibility aspect if you don't mind. I've provided a quick reply on the original metadata issue, and it'll be addressed in due time, without needing extensibility itself.

As per the last comment on the partial aspect. On a technical standpoint, I don't have a strong opposition to make things partial in C#. On a product management aspect, I'm more concerned however. This is because we might back ourselves into a corner:
1. We make things partial in dotnet,
2. People build all kind of extensibility over that.
3. Now people want to port those extensions to Java, and it's not possible.
4. We'd need to either tell them "go complain to the core language team" or "not possible" both stances make for a really poor experience.

This is why I was suggesting you engage on the thread I linked originally.

**Comment by svrooij** [comment]
> 4. We'd need to either tell them "go complain to the core language team" or "not possible" both stances make for a really poor experience.

Or give it a positive turn:

## Language specific additional features ⭐

Clients generated by Kiota also have some specific features that don't work on all platforms, because either that language does not support it or we did not implemented it in that language, and we are accepting pr's.

| Feature | C# | TypeScript | Java | ... |
|--------- |---  |----------    |---|---|
| Request Builder extensibility | ✅ through partials | ✅ by extending the class | ❌ core language | ... |

**Comment by baywet** [comment]
Again, all valid points, please bring those on the issue I linked.
Closing since we're not doing that work for now until a decision on extensibility has been reached.
