### ISSUE TITLE
Generate DateOnly type for newer .net releases

### ISSUE THREAD

**Issue by jods4** [microsoft/kiota-abstractions-dotnet#115]
For `{ type: "string", format: "date" }` models, Kiota references a `Date` struct that is shipped in its Abstractions package.

In newer .net releases, it would be nice to use the built-in `System.DateOnly` type, so that the model integrates more naturally with the rest of the code.

**Comment by baywet** [comment]
CC @andrueastman for review of the approach here.
@jods4 would you be interested in submitting a pull request for this now that we have clear directions?

**Comment by jods4** [comment]
Yes, I can PR conversion operators.

Question though: why do you suggest _explicit_ conversion to Date?
This means we have to write `QueryParameters.StartDate = (Date)startDate` instead of `QueryParameters.StartDate = startDate` (assuming `startDate` is a `DateOnly`).

> Is this failing because of the code we intended to be there or some additional third party extensibility?

Nothing crucial so far. I was looking to extend the main class (which I did by subclassing).
Subclassing is ok with client because I have control over instantiation. I don't have an extensibility need for model classes yet, but as they are instantiated by generated code, partial class is the only way to extend them.
Other use cases you can't solve with subclasses would be adding attributes on existing members.

**Comment by baywet** [comment]
Updated my original comment to implicit for all. I don't think we'll suffer loss of precision either way. So we shouldn't require the user to make an explicit conversion.

**Comment by 0xced** [comment]
I just submitted #249 which adds support for `DateOnly` and `TimeOnly`.
