### ISSUE TITLE
downgrade kiota libraries (and graph SDK) to netstandard2.0

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-abstractions-dotnet#12]
The Kiota libraries are currently targeting netstandard2.1, which is not supported by dotnet framework (classic).
This makes for a steep adoption curve for people who have existing projects.
I don't believe we actually need 2.1, I think the history there is that we created the projects with net5.0 at the time, and then downgraded to standard 2.1 when came time to reach public preview.

[netstandard2.0](https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0) should bring the libs back to compatibility with the framework (classic).

If we're using something specific to 2.1, the alternative would be to multi-target 2.1, and 4.6.2, 4.7.2 and 4.8.

**Comment by baywet** [comment]
thanks for taking the time to tackle this.
it seems that during this PR https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/408 we forgot to rev down the standard version. Would you mind pushing another preview for this one so we can roll it all the way to the service lib please?

**Comment by andrueastman** [comment]
Hey @baywet.
I still have some work to do for the core lib hence https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/408 didn't do the drop.
I'll hopefully close this today then we can close this issue.

**Comment by andrueastman** [comment]
Graph SDK changes made via 

- https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/pull/411
- https://github.com/microsoftgraph/msgraph-sdk-dotnet/pull/1315
- https://github.com/microsoftgraph/msgraph-beta-sdk-dotnet/pull/429

**Comment by baywet** [comment]
Thanks! Closing as those were merged too!
