### ISSUE TITLE
Published kiota packages depend on DiagnosticSource < 8.0.0

### ISSUE THREAD

**Issue by charlesroddie** [microsoft/kiota-abstractions-dotnet#149]
kiota packages such as `Microsoft.Kiota.Abstractions 1.7.1` (published today) require `System.Diagnostics.DiagnosticSource (>= 6.0.0 && < 8.0.0)`.

The explicit failure to work with 8.0.0 creates a lot of problems for packages released together with dotnet 8 which bring in `DiagnosticSource 8.0.0`. For example we get build failures with `Microsoft.Extensions.Http 8.0.0 -> Microsoft.Extensions.Diagnostics 8.0.0 -> Microsoft.Extensions.Diagnostics.Abstractions 8.0.0 -> System.Diagnostics.DiagnosticSource (>= 8.0.0) `.

**Comment by baywet** [comment]
Thank you for using kiota and for reaching out.
I just put together #150 to start the process here.
We'll need to cascade the changes. For this to be entirely available, see https://github.com/microsoft/kiota-serialization-json-dotnet/issues/105
