### ISSUE TITLE
Serialization/Deserialization of Date format

### ISSUE THREAD

**Issue by hayama600** [microsoft/kiota-abstractions-dotnet#178]
I have Request class with Date datatype property.
When sending in request Date api expects it  in format DD.MM.YYYY, and sending back Date in that format.
Is it possible to do that without changing generated code?

		var client = new PostsClient(httpClientRequestAdapter);

		var body = new Request()
		{
			PromjenaOd = new Microsoft.Kiota.Abstractions.Date(2020, 01, 01),
		};
		var response =  await client.Shema.GetStates.PostAsync(body,null);
		response.Dump();
		}

**Comment by baywet** [comment]
Yep, that's pretty much the only option here. And it should work across all languages.
@hayama600 do you think you'd be willing to send a pull request for that?

1. add an optional format parameter [here](https://github.com/microsoft/kiota-abstractions-dotnet/blob/3a88c8f890123229e37effd8e13a8fbc5696dbbc/src/Date.cs#L18), default the value to what we have [here](https://github.com/microsoft/kiota-abstractions-dotnet/blob/3a88c8f890123229e37effd8e13a8fbc5696dbbc/src/Date.cs#L78)
2. assign the parameter to a new "Format" property.
3. add the format optional parameter to [this constructor as well](https://github.com/microsoft/kiota-abstractions-dotnet/blob/3a88c8f890123229e37effd8e13a8fbc5696dbbc/src/Date.cs#L29) and pass it to the other one.
4. use the Format property [in the toString method](https://github.com/microsoft/kiota-abstractions-dotnet/blob/3a88c8f890123229e37effd8e13a8fbc5696dbbc/src/Date.cs#L78) (throw if null or empty)
5. add a couple of unit tests in the tests project
6. do the same for the Time struct

Let us know if you have any question!

**Comment by hayama600** [comment]
> Yep, that's pretty much the only option here. And it should work across all languages. @hayama600 do you think you'd be willing to send a pull request for that?
> 
> 1. add an optional format parameter [here](https://github.com/microsoft/kiota-abstractions-dotnet/blob/3a88c8f890123229e37effd8e13a8fbc5696dbbc/src/Date.cs#L18), default the value to what we have [here](https://github.com/microsoft/kiota-abstractions-dotnet/blob/3a88c8f890123229e37effd8e13a8fbc5696dbbc/src/Date.cs#L78)
> 2. assign the parameter to a new "Format" property.
> 3. add the format optional parameter to [this constructor as well](https://github.com/microsoft/kiota-abstractions-dotnet/blob/3a88c8f890123229e37effd8e13a8fbc5696dbbc/src/Date.cs#L29) and pass it to the other one.
> 4. use the Format property [in the toString method](https://github.com/microsoft/kiota-abstractions-dotnet/blob/3a88c8f890123229e37effd8e13a8fbc5696dbbc/src/Date.cs#L78) (throw if null or empty)
> 5. add a couple of unit tests in the tests project
> 6. do the same for the Time struct
> 
> Let us know if you have any question!

I will create a pull request next week; I'll reach out if I have any questions.

**Comment by andrueastman** [comment]
@hayama600 Any chance you can still take a look at this?
