### ISSUE TITLE
Project condition for IsTrimmable is incorrect

### ISSUE THREAD

**Issue by hwoodiwiss** [microsoft/kiota-abstractions-dotnet#188]
## Current Behaviour
Currently `IsTrimmable` is not set on a number of the Microsoft.Kiota .NET libraries as they share this incorrect condition:

```xml
<PropertyGroup Condition="'$(TargetFrameworkVersion)' == 'net5.0'">  
  <IsTrimmable>true</IsTrimmable>
</PropertyGroup>
```

## Expected Behaviour

I would expect build errors when non-trim-safe code as added to the libraries.

## Fix

The property group condition should be changed to:
```xml
<PropertyGroup Condition="'$(TargetFramework)' == 'net5.0'">  
  <IsTrimmable>true</IsTrimmable>
</PropertyGroup>
```
Which causes the `IsTrimmable` property to be correctly set, and any expected trimming related compilation failures to occur.

I've found this issue in these projects:

- [ ] - [Microsoft.Kiota.Abstractions](https://github.com/microsoft/kiota-abstractions-dotnet/blob/HEAD/src/Microsoft.Kiota.Abstractions.csproj#L37) ([In PR](https://github.com/microsoft/kiota-abstractions-dotnet/pull/187))
- [ ]  - [Microsoft.Kiota.Http.HttpClientLibrary](https://github.com/microsoft/kiota-http-dotnet/blob/HEAD/src/Microsoft.Kiota.Http.HttpClientLibrary.csproj#L37) ([In PR](https://github.com/microsoft/kiota-http-dotnet/pull/201))
- [ ] - [Microsoft.Kiota.Serialization.Json](https://github.com/microsoft/kiota-serialization-json-dotnet/blob/HEAD/src/Microsoft.Kiota.Serialization.Json.csproj#L37) ([In PR](https://github.com/microsoft/kiota-serialization-json-dotnet/pull/178))
- [ ] - [Microsoft.Kiota.Serialization.Form](https://github.com/microsoft/kiota-serialization-form-dotnet/blob/HEAD/src/Microsoft.Kiota.Serialization.Form.csproj#L39) ([In PR](https://github.com/microsoft/kiota-serialization-form-dotnet/pull/110))
- [ ] - [Microsoft.Kiota.Authentication.Azure](https://github.com/microsoft/kiota-authentication-azure-dotnet/blob/HEAD/src/Microsoft.Kiota.Authentication.Azure.csproj#L37)
- [ ] - [Microsoft.Kiota.Serialization.Multipart](https://github.com/microsoft/kiota-serialization-multipart-dotnet/blob/HEAD/src/Microsoft.Kiota.Serialization.Multipart.csproj#L37) ([In PR](https://github.com/microsoft/kiota-serialization-multipart-dotnet/pull/63))
- [ ] - [Microsoft.Kiota.Serialization.Text](https://github.com/microsoft/kiota-serialization-text-dotnet/blob/HEAD/src/Microsoft.Kiota.Serialization.Text.csproj#L36) ([In PR](https://github.com/microsoft/kiota-serialization-text-dotnet/pull/140))

**Comment by baywet** [comment]
For additional context: while the property being used [exists in some contexts](https://learn.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2022) it seems it wasn't the right one https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#targetframework

Additional evidence
https://www.aloneguid.uk/posts/2022/08/csproj-condition-cheat-sheet/
