### ISSUE TITLE
Guid uri template path/query parameter values should be normalized to string

### ISSUE THREAD

**Issue by baywet** [microsoft/kiota-abstractions-dotnet#209]
the std uri template library does not handle guids, and wont because it's not a standard API across languages and they don't want to bring on additional dependencies.
We should normalize the value to string (no curlies) before we pass it to the uri template engine.
Originally reported:
https://github.com/std-uritemplate/std-uritemplate/issues/140
https://github.com/microsoft/kiota/issues/4335

**Comment by andrueastman** [comment]
@baywet I believe this is already happening in the abstraction library at https://github.com/microsoft/kiota-abstractions-dotnet/blob/5a93d126e9ce30ae332e65f30df7b941e7d7c265/src/RequestInformation.cs#L128 and this could potentially be closed.

Validated at 
- https://github.com/microsoft/kiota-abstractions-dotnet/blob/5a93d126e9ce30ae332e65f30df7b941e7d7c265/Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs#L196
- https://github.com/microsoft/kiota-abstractions-dotnet/blob/5a93d126e9ce30ae332e65f30df7b941e7d7c265/Microsoft.Kiota.Abstractions.Tests/RequestInformationTests.cs#L646

**Comment by baywet** [comment]
Ah, so we only did that in dotnet... thank you for the pointer. Closing
