### ISSUE TITLE
Remove System.Diagnostics.DiagnosticSource dependency from net 6+

### ISSUE THREAD

**Issue by thompson-tomo** [microsoft/kiota-abstractions-dotnet#218]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Diagnostics.DiagnosticSource on net 6+. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by andrueastman** [comment]
Thanks for raising this @thompson-tomo 

Would you be willing to submit a PR similar to https://github.com/microsoft/kiota-abstractions-dotnet/issues/219 for this?

**Comment by thompson-tomo** [comment]
@andrueastman sure I will go through submitting PR's in the coming days.

**Comment by thompson-tomo** [comment]
Submitted as #220
