### ISSUE TITLE
Set Licence expression on package

### ISSUE THREAD

**Issue by thompson-tomo** [microsoft/kiota-abstractions-dotnet#219]
### Summary
I wish for the nuget packages to have the licence expression property set correctly

### Details

The licence expression property should be set to the correct licence type I.e. MIT as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc.

**Comment by andrueastman** [comment]
Thanks for raising this @thompson-tomo 

Would you be willing to submit a PR for this? I assume what you mean is setting the `PackageLicenseExpression` in the csproj file. Yes?

**Comment by thompson-tomo** [comment]
@andrueastman sure I will go through submitting PR's in the coming days.

**Comment by baywet** [comment]
Here is some [additional context](https://github.com/std-uritemplate/std-uritemplate/pull/163#pullrequestreview-2005796285) on the nature of the change
