### ISSUE TITLE
Avoid using GetAwaiter().GetResult() to prevent deadlocks

### ISSUE THREAD

**Issue by MihaMarkic** [microsoft/kiota-abstractions-dotnet#226]
Getting synchronously results from async functions is quite an issue and should be avoided. Specially in a UI thread environments as described in Stephen's [blog post](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).
Sample code in `KiotaSerializer.GetStreamFromString` method:
```csharp
// Some clients enforce async stream processing.
writer.WriteAsync(source).GetAwaiter().GetResult();
```

I guess once async overloads are added (#223), this code could be made pure sync and when async is required, a dedicated function can be used instead. Albeit it might cause breaking changes.

**Comment by MihaMarkic** [comment]
Even better, IMO

**Comment by andrueastman** [comment]
No objections from my side. The functions are already not `async` so making them purely sync is what we should do here really.

**Comment by MihaMarkic** [comment]
Deserialization is taken care with [#225](https://github.com/microsoft/kiota-abstractions-dotnet/pull/225)

**Comment by baywet** [comment]
Thanks for the update.
I guess at this point the only missing part would be to change that to the sync overload.
https://github.com/microsoft/kiota-abstractions-dotnet/blob/56efcdf4227baef8ee75adc342f06e23e96ab3fb/src/serialization/KiotaSerializer.Serialization.cs#L104

Would you mind sending one last PR our way to wrap this aspect up?

**Comment by MihaMarkic** [comment]
@baywet Sure, created. Do you need also version bump?
