### ISSUE TITLE
Please support trimming for self contained projects

### ISSUE THREAD

**Issue by zachcwillson** [microsoft/kiota-abstractions-dotnet#77]
When building a dotnet 7 self-contained project with Graph Beta SDK 5.24.0-preview, the following warning is observed:
```
C:\Users\{user}\.nuget\packages\microsoft.kiota.abstractions\1.1.0\lib\netstandard2.1\Microsoft.Kiota.Abstractions.dll : warning IL2104: Assembly 'Mi
crosoft.Kiota.Abstractions' produced trim warnings. For more information see https://aka.ms/dotnet-illink/libraries [C:\Users\{user}\source\repos\{project}.csproj]
```
Ideally, this warning would be resolved by supporting Trimming in the package - see https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2104

**Comment by andrueastman** [comment]
Resolved via https://github.com/microsoft/kiota-abstractions-dotnet/pull/139
